### ISSUE TITLE
Client should be the one to add guards for rake-ui

### ISSUE THREAD

**Issue by jlurena** [doximity/rake-ui#18]
Remove guards.

ie: We deploy lower test environments with RAILS_ENV=production or RAILS_ENV=staging. These guards can be added at routes definition.

**Comment by Austio** [comment]
Thanks for bringing up and sorry for missing the discussion.  You can now handle this in 0.1.0 through a configuration to enable in prod.

https://github.com/doximity/rake-ui/releases/tag/v0.1.0
